/*
This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with this program. If not, see <https://www.gnu.org/licenses/>. 
*/

#include "asmdefs.h"

/*
 _______________________________________________
| F| E| D| C| B| A| 9| 8| 7| 6| 5| 4| 3| 2| 1| 0|
 if P=9           |_P|__________________________
 ________________ |______________ WP____________|
|_____________________ W________________________|
|_S|__________________M________________|XS|__B__|
                                 |_______A______|
                                    |_____X_____|
*/

/*
  fields        P WP XS  X  S  M  B  W  A
  FLAG_A_FIELD  0  1  2  3  4  5  6  7  -
  FLAG_B_FIELD  8  9  A  B  C  D  E  F  -
  FLAG_F_FIELD  0  1  2  3  4  5  6  7  F
*/
char field_a[33] = " PWPXS X S M B W----------------";
char field_b[33] = "---------------- PWPXS X S M B W";
char field_f[33] = " PWPXS X S M B W-------------- A";

/* Used as reference 'Voyage au centre de la HP48g/gx' - Paul Courbis */
const struct instr instructions[] = {
	/* TODO add known paterns as
"B+=C*A A":
*MULT ?CBIT=0 GOYES NP
      B=C+B A
*NP   A=A-1 A
      ASRB A
      ?C!=0 A GOYES MULT
	*/

	{  .sl = 2, .v = { 0x0, 0x0 }, .name = "RTNYES" },
	{  .sl = 2, .v = { 0x0, 0x0 }, .name = "RTNSXM" },
	{  .sl = 2, .v = { 0x0, 0x1 }, .name = "RTN" },
	{  .sl = 2, .v = { 0x0, 0x2 }, .name = "RTNSC" },
	{  .sl = 2, .v = { 0x0, 0x3 }, .name = "RTNCC" },
	{  .sl = 2, .v = { 0x0, 0x4 }, .name = "SETHEX" },
	{  .sl = 2, .v = { 0x0, 0x5 }, .name = "SETDEC" },
	{  .sl = 2, .v = { 0x0, 0x6 }, .name = "RSTK=C" },
	{  .sl = 2, .v = { 0x0, 0x7 }, .name = "C=RSTK" },
	{  .sl = 2, .v = { 0x0, 0x8 }, .name = "CLRST" },
	{  .sl = 2, .v = { 0x0, 0x9 }, .name = "C=ST" },
	{  .sl = 2, .v = { 0x0, 0xA }, .name = "ST=C" },
	{  .sl = 2, .v = { 0x0, 0xB }, .name = "CSTEX" },
	{  .sl = 2, .v = { 0x0, 0xC }, .name = "P=P+1" },
	{  .sl = 2, .v = { 0x0, 0xD }, .name = "P=P-1" },

	{  .sl = 4, .v = { 0x0, 0xE, FLAG_F_FIELD, 0x0 }, .name = "A=A&B" },
	{  .sl = 4, .v = { 0x0, 0xE, FLAG_F_FIELD, 0x1 }, .name = "B=B&C" },
	{  .sl = 4, .v = { 0x0, 0xE, FLAG_F_FIELD, 0x2 }, .name = "C=C&A" },
	{  .sl = 4, .v = { 0x0, 0xE, FLAG_F_FIELD, 0x3 }, .name = "D=D&C" },
	{  .sl = 4, .v = { 0x0, 0xE, FLAG_F_FIELD, 0x4 }, .name = "B=B&A" },
	{  .sl = 4, .v = { 0x0, 0xE, FLAG_F_FIELD, 0x5 }, .name = "C=C&B" },
	{  .sl = 4, .v = { 0x0, 0xE, FLAG_F_FIELD, 0x6 }, .name = "A=A&C" },
	{  .sl = 4, .v = { 0x0, 0xE, FLAG_F_FIELD, 0x7 }, .name = "C=C&D" },
	{  .sl = 4, .v = { 0x0, 0xE, FLAG_F_FIELD, 0x8 }, .name = "A=A!B" },
	{  .sl = 4, .v = { 0x0, 0xE, FLAG_F_FIELD, 0x9 }, .name = "B=B!C" },
	{  .sl = 4, .v = { 0x0, 0xE, FLAG_F_FIELD, 0xA }, .name = "C=C!A" },
	{  .sl = 4, .v = { 0x0, 0xE, FLAG_F_FIELD, 0xB }, .name = "D=D!C" },
	{  .sl = 4, .v = { 0x0, 0xE, FLAG_F_FIELD, 0xC }, .name = "B=B!A" },
	{  .sl = 4, .v = { 0x0, 0xE, FLAG_F_FIELD, 0xD }, .name = "C=C!B" },
	{  .sl = 4, .v = { 0x0, 0xE, FLAG_F_FIELD, 0xE }, .name = "A=A!C" },
	{  .sl = 4, .v = { 0x0, 0xE, FLAG_F_FIELD, 0xF }, .name = "C=C!D" },
	{  .sl = 2, .v = { 0x0, 0xF }, .name = "RTI" },

	/* 100 to 11C defined at end to detect first if a field is specified */
	{  .sl = 3, .v = { 0x1, 0x2, 0x0 }, .name = "AR0EX" },
	{  .sl = 3, .v = { 0x1, 0x2, 0x1 }, .name = "AR1EX" },
	{  .sl = 3, .v = { 0x1, 0x2, 0x2 }, .name = "AR2EX" },
	{  .sl = 3, .v = { 0x1, 0x2, 0x3 }, .name = "AR3EX" },
	{  .sl = 3, .v = { 0x1, 0x2, 0x4 }, .name = "AR4EX" },
	{  .sl = 3, .v = { 0x1, 0x2, 0x8 }, .name = "CR0EX" },
	{  .sl = 3, .v = { 0x1, 0x2, 0x9 }, .name = "CR1EX" },
	{  .sl = 3, .v = { 0x1, 0x2, 0xA }, .name = "CR2EX" },
	{  .sl = 3, .v = { 0x1, 0x2, 0xB }, .name = "CR3EX" },
	{  .sl = 3, .v = { 0x1, 0x2, 0xC }, .name = "CR4EX" },
	{  .sl = 3, .v = { 0x1, 0x3, 0x0 }, .name = "D0=A" },
	{  .sl = 3, .v = { 0x1, 0x3, 0x1 }, .name = "D1=A" },
	{  .sl = 3, .v = { 0x1, 0x3, 0x2 }, .name = "AD0EX" },
	{  .sl = 3, .v = { 0x1, 0x3, 0x3 }, .name = "AD1EX" },
	{  .sl = 3, .v = { 0x1, 0x3, 0x4 }, .name = "D0=C" },
	{  .sl = 3, .v = { 0x1, 0x3, 0x5 }, .name = "D1=C" },
	{  .sl = 3, .v = { 0x1, 0x3, 0x6 }, .name = "CD0EX" },
	{  .sl = 3, .v = { 0x1, 0x3, 0x7 }, .name = "CD1EX" },
	{  .sl = 3, .v = { 0x1, 0x3, 0x8 }, .name = "D0=AS" },
	{  .sl = 3, .v = { 0x1, 0x3, 0x9 }, .name = "DA=AS" },
	{  .sl = 3, .v = { 0x1, 0x3, 0xA }, .name = "AD0XS" },
	{  .sl = 3, .v = { 0x1, 0x3, 0xB }, .name = "AD1XS" },
	{  .sl = 3, .v = { 0x1, 0x3, 0xC }, .name = "D0=CS" },
	{  .sl = 3, .v = { 0x1, 0x3, 0xD }, .name = "DA=CS" },
	{  .sl = 3, .v = { 0x1, 0x3, 0xE }, .name = "CD0XS" },
	{  .sl = 3, .v = { 0x1, 0x3, 0xF }, .name = "CD1XS" },
	{  .sl = 3, .v = { 0x1, 0x4, 0x0 }, .name = "DAT0=A A" },
	{  .sl = 3, .v = { 0x1, 0x4, 0x1 }, .name = "DAT1=A A" },
	{  .sl = 3, .v = { 0x1, 0x4, 0x2 }, .name = "A=DAT0 A" },
	{  .sl = 3, .v = { 0x1, 0x4, 0x3 }, .name = "A=DAT1 A" },
	{  .sl = 3, .v = { 0x1, 0x4, 0x4 }, .name = "DAT0=C A" },
	{  .sl = 3, .v = { 0x1, 0x4, 0x5 }, .name = "DAT1=C A" },
	{  .sl = 3, .v = { 0x1, 0x4, 0x6 }, .name = "C=DAT0 A" },
	{  .sl = 3, .v = { 0x1, 0x4, 0x7 }, .name = "C=DAT1 A" },
	{  .sl = 3, .v = { 0x1, 0x4, 0x8 }, .name = "DAT0=A B" },
	{  .sl = 3, .v = { 0x1, 0x4, 0x9 }, .name = "DAT1=A B" },
	{  .sl = 3, .v = { 0x1, 0x4, 0xA }, .name = "A=DAT0 B" },
	{  .sl = 3, .v = { 0x1, 0x4, 0xB }, .name = "A=DAT1 B" },
	{  .sl = 3, .v = { 0x1, 0x4, 0xC }, .name = "DAT0=C B" },
	{  .sl = 3, .v = { 0x1, 0x4, 0xD }, .name = "DAT1=C B" },
	{  .sl = 3, .v = { 0x1, 0x4, 0xE }, .name = "C=DAT0 B" },
	{  .sl = 3, .v = { 0x1, 0x4, 0xF }, .name = "C=DAT1 B" },

	{  .sl = 4, .v = { 0x1, 0x5, 0x0, FLAG_A_FIELD }, .name = "DAT0=A" },
	{  .sl = 4, .v = { 0x1, 0x5, 0x1, FLAG_A_FIELD }, .name = "DAT1=A" },
	{  .sl = 4, .v = { 0x1, 0x5, 0x2, FLAG_A_FIELD }, .name = "A=DAT0" },
	{  .sl = 4, .v = { 0x1, 0x5, 0x3, FLAG_A_FIELD }, .name = "A=DAT1" },
	{  .sl = 4, .v = { 0x1, 0x5, 0x4, FLAG_A_FIELD }, .name = "DAT0=C" },
	{  .sl = 4, .v = { 0x1, 0x5, 0x5, FLAG_A_FIELD }, .name = "DAT1=C" },
	{  .sl = 4, .v = { 0x1, 0x5, 0x6, FLAG_A_FIELD }, .name = "C=DAT0" },
	{  .sl = 4, .v = { 0x1, 0x5, 0x7, FLAG_A_FIELD }, .name = "C=DAT1" },
	{  .sl = 4, .v = { 0x1, 0x5, 0x8, FLAG_X1 }, .name = "DAT0=A" },
	{  .sl = 4, .v = { 0x1, 0x5, 0x9, FLAG_X1 }, .name = "DAT1=A" },
	{  .sl = 4, .v = { 0x1, 0x5, 0xA, FLAG_X1 }, .name = "A=DAT0" },
	{  .sl = 4, .v = { 0x1, 0x5, 0xB, FLAG_X1 }, .name = "A=DAT1" },
	{  .sl = 4, .v = { 0x1, 0x5, 0xC, FLAG_X1 }, .name = "DAT0=C" },
	{  .sl = 4, .v = { 0x1, 0x5, 0xD, FLAG_X1 }, .name = "DAT1=C" },
	{  .sl = 4, .v = { 0x1, 0x5, 0xE, FLAG_X1 }, .name = "C=DAT0" },
	{  .sl = 4, .v = { 0x1, 0x5, 0xF, FLAG_X1 }, .name = "C=DAT1" },
	{  .sl = 3, .v = { 0x1, 0x6, FLAG_N1 }, .name = "D0=D0+" },
	{  .sl = 3, .v = { 0x1, 0x7, FLAG_N1 }, .name = "D1=D1+" },
	{  .sl = 3, .v = { 0x1, 0x8, FLAG_N1 }, .name = "D0=D0-" },
	{  .sl = 3, .v = { 0x1, 0x9, FLAG_PTR2}, .name = "D0=(2)" },
	{  .sl = 3, .v = { 0x1, 0xA, FLAG_PTR4}, .name = "D0=(4)" },
	{  .sl = 3, .v = { 0x1, 0xB, FLAG_PTR5}, .name = "D0=(5)" },
	{  .sl = 3, .v = { 0x1, 0xB, FLAG_PTR5}, .name = "D0=" },
	{  .sl = 3, .v = { 0x1, 0xC, FLAG_N1 }, .name = "D1=D1-" },
	{  .sl = 3, .v = { 0x1, 0xD, FLAG_PTR2}, .name = "D1=(2)" },
	{  .sl = 3, .v = { 0x1, 0xE, FLAG_PTR4}, .name = "D1=(4)" },
	{  .sl = 3, .v = { 0x1, 0xF, FLAG_PTR5}, .name = "D1=(5)" },
	{  .sl = 3, .v = { 0x1, 0xF, FLAG_PTR5}, .name = "D1=" },

	{  .sl = 2, .v = { 0x3, FLAG_VAR }, .name = "LCHEX" },
	{  .sl = 2, .v = { 0x3, FLAG_VAR }, .name = "LC" },

	{  .sl = 3, .v = { 0x4, 0x0, 0x0}, .name = "RTNC" },
	{  .sl = 3, .v = { 0x4, 0x2, 0x0}, .name = "NOP3" },
	{  .sl = 2, .v = { 0x4, FLAG_ADDR2}, .name = "GOC" },

	{  .sl = 3, .v = { 0x5, 0x0, 0x0}, .name = "RTNNC" },
	{  .sl = 2, .v = { 0x5, FLAG_ADDR2 }, .name = "GONC" },

	{  .sl = 4, .v = { 0x6, 0x3, 0x0, 0x0}, .name = "NOP4" },
	{  .sl = 4, .v = { 0x6, 0x4, 0x0, 0x0, 0x0}, .name = "NOP5" },
	{  .sl = 2, .v = { 0x6, FLAG_ADDR3 }, .name = "GOTO" },

	{  .sl = 2, .v = { 0x7, FLAG_ADDR3SUB }, .name = "GOSUB" },

	{  .sl = 3, .v = { 0x8, 0x0, 0x0 }, .name = "OUT=CS" },
	{  .sl = 3, .v = { 0x8, 0x0, 0x1 }, .name = "OUT=C" },
	{  .sl = 3, .v = { 0x8, 0x0, 0x2 }, .name = "A=IN" },
	{  .sl = 3, .v = { 0x8, 0x0, 0x3 }, .name = "C=IN" },
	{  .sl = 3, .v = { 0x8, 0x0, 0x4 }, .name = "UNCNFG" },
	{  .sl = 3, .v = { 0x8, 0x0, 0x5 }, .name = "CONFIG" },
	{  .sl = 3, .v = { 0x8, 0x0, 0x6 }, .name = "C=ID" },
	{  .sl = 3, .v = { 0x8, 0x0, 0x7 }, .name = "SHUTDN" },
	{  .sl = 4, .v = { 0x8, 0x0, 0x8, 0x0 }, .name = "INTON" },
	{  .sl = 5, .v = { 0x8, 0x0, 0x8, 0x1, 0x0 }, .name = "RSI" },
	{  .sl = 5, .v = { 0x8, 0x0, 0x8, 0x2, FLAG_VAR }, .name = "LAHEX" },
	{  .sl = 5, .v = { 0x8, 0x0, 0x8, 0x2, FLAG_VAR }, .name = "LA" },
	{  .sl = 4, .v = { 0x8, 0x0, 0x8, 0x3 }, .name = "BUSCB" },
	{  .sl = 5, .v = { 0x8, 0x0, 0x8, 0x4, FLAG_BIT_INDEX }, .name = "ABIT=0" },
	{  .sl = 5, .v = { 0x8, 0x0, 0x8, 0x5, FLAG_BIT_INDEX }, .name = "ABIT=1" },
	{  .sl = 6, .v = { 0x8, 0x0, 0x8, 0x6, FLAG_BIT_INDEX, FLAG_ADDR2}, .name = "?ABIT=0" },
	{  .sl = 6, .v = { 0x8, 0x0, 0x8, 0x7, FLAG_BIT_INDEX, FLAG_ADDR2}, .name = "?ABIT=1" },
	{  .sl = 5, .v = { 0x8, 0x0, 0x8, 0x8, FLAG_BIT_INDEX }, .name = "CBIT=0" },
	{  .sl = 5, .v = { 0x8, 0x0, 0x8, 0x9, FLAG_BIT_INDEX }, .name = "CBIT=1" },
	{  .sl = 6, .v = { 0x8, 0x0, 0x8, 0xA, FLAG_BIT_INDEX, FLAG_ADDR2}, .name = "?CBIT=0" },
	{  .sl = 6, .v = { 0x8, 0x0, 0x8, 0xB, FLAG_BIT_INDEX, FLAG_ADDR2}, .name = "?CBIT=1" },
	{  .sl = 4, .v = { 0x8, 0x0, 0x8, 0xC }, .name = "PC=(A)" },
	{  .sl = 4, .v = { 0x8, 0x0, 0x8, 0xD }, .name = "BUSD" },
	{  .sl = 4, .v = { 0x8, 0x0, 0x8, 0xE }, .name = "PC=(C)" },
	{  .sl = 4, .v = { 0x8, 0x0, 0x8, 0xF }, .name = "INTOFF" },
	{  .sl = 3, .v = { 0x8, 0x0, 0x9 }, .name = "C=P+1" },
	{  .sl = 3, .v = { 0x8, 0x0, 0xA }, .name = "RESET" },
	{  .sl = 3, .v = { 0x8, 0x0, 0xB }, .name = "BUSCC" },
	{  .sl = 4, .v = { 0x8, 0x0, 0xC, FLAG_BIT_INDEX }, .name = "C=P" },
	{  .sl = 4, .v = { 0x8, 0x0, 0xD, FLAG_BIT_INDEX }, .name = "P=C" },

	/* detect first 'P=C' */
	{  .sl = 2, .v = { 0x2, FLAG_N }, .name = "P=" },

	{  .sl = 4, .v = { 0x8, 0x0, 0xE, FLAG_ADDR2 }, .name = "?SREQ" },
	{  .sl = 4, .v = { 0x8, 0x0, 0xF, FLAG_BIT_INDEX }, .name = "CPEX" },

	{  .sl = 3, .v = { 0x8, 0x1, 0x0 }, .name = "ASLC" },
	{  .sl = 3, .v = { 0x8, 0x1, 0x1 }, .name = "BSLC" },
	{  .sl = 3, .v = { 0x8, 0x1, 0x2 }, .name = "CSLC" },
	{  .sl = 3, .v = { 0x8, 0x1, 0x3 }, .name = "DSLC" },
	{  .sl = 3, .v = { 0x8, 0x1, 0x4 }, .name = "ASRC" },
	{  .sl = 3, .v = { 0x8, 0x1, 0x5 }, .name = "BSRC" },
	{  .sl = 3, .v = { 0x8, 0x1, 0x6 }, .name = "CSRC" },
	{  .sl = 3, .v = { 0x8, 0x1, 0x7 }, .name = "DSRC" },

	{  .sl = 5, .v = { 0x8, 0x1, 0x9, FLAG_F_FIELD, 0x0 }, .name = "ASRB" },
	{  .sl = 5, .v = { 0x8, 0x1, 0x9, FLAG_F_FIELD, 0x1 }, .name = "BSRB" },
	{  .sl = 5, .v = { 0x8, 0x1, 0x9, FLAG_F_FIELD, 0x2 }, .name = "CSRB" },
	{  .sl = 5, .v = { 0x8, 0x1, 0x9, FLAG_F_FIELD, 0x3 }, .name = "DSRB" },
	{  .sl = 5, .v = { 0x8, 0x1, 0x9, FLAG_F_FIELD, 0x0 }, .name = "ASRB.F" },
	{  .sl = 5, .v = { 0x8, 0x1, 0x9, FLAG_F_FIELD, 0x1 }, .name = "BSRB.F" },
	{  .sl = 5, .v = { 0x8, 0x1, 0x9, FLAG_F_FIELD, 0x2 }, .name = "CSRB.F" },
	{  .sl = 5, .v = { 0x8, 0x1, 0x9, FLAG_F_FIELD, 0x3 }, .name = "DSRB.F" },

	{  .sl = 6, .v = { 0x8, 0x1, 0xA, FLAG_F_FIELD, 0x0, 0x0}, .name = "R0=A" },
	{  .sl = 6, .v = { 0x8, 0x1, 0xA, FLAG_F_FIELD, 0x0, 0x1}, .name = "R1=A" },
	{  .sl = 6, .v = { 0x8, 0x1, 0xA, FLAG_F_FIELD, 0x0, 0x2}, .name = "R2=A" },
	{  .sl = 6, .v = { 0x8, 0x1, 0xA, FLAG_F_FIELD, 0x0, 0x3}, .name = "R3=A" },
	{  .sl = 6, .v = { 0x8, 0x1, 0xA, FLAG_F_FIELD, 0x0, 0x4}, .name = "R4=A" },
	{  .sl = 6, .v = { 0x8, 0x1, 0xA, FLAG_F_FIELD, 0x0, 0x8}, .name = "R0=C" },
	{  .sl = 6, .v = { 0x8, 0x1, 0xA, FLAG_F_FIELD, 0x0, 0x9}, .name = "R1=C" },
	{  .sl = 6, .v = { 0x8, 0x1, 0xA, FLAG_F_FIELD, 0x0, 0xA}, .name = "R2=C" },
	{  .sl = 6, .v = { 0x8, 0x1, 0xA, FLAG_F_FIELD, 0x0, 0xB}, .name = "R3=C" },
	{  .sl = 6, .v = { 0x8, 0x1, 0xA, FLAG_F_FIELD, 0x0, 0xC}, .name = "R4=C" },
	{  .sl = 6, .v = { 0x8, 0x1, 0xA, FLAG_F_FIELD, 0x1, 0x0}, .name = "A=R0" },
	{  .sl = 6, .v = { 0x8, 0x1, 0xA, FLAG_F_FIELD, 0x1, 0x1}, .name = "A=R1" },
	{  .sl = 6, .v = { 0x8, 0x1, 0xA, FLAG_F_FIELD, 0x1, 0x2}, .name = "A=R2" },
	{  .sl = 6, .v = { 0x8, 0x1, 0xA, FLAG_F_FIELD, 0x1, 0x3}, .name = "A=R3" },
	{  .sl = 6, .v = { 0x8, 0x1, 0xA, FLAG_F_FIELD, 0x1, 0x4}, .name = "A=R4" },
	{  .sl = 6, .v = { 0x8, 0x1, 0xA, FLAG_F_FIELD, 0x1, 0x8}, .name = "C=R0" },
	{  .sl = 6, .v = { 0x8, 0x1, 0xA, FLAG_F_FIELD, 0x1, 0x9}, .name = "C=R1" },
	{  .sl = 6, .v = { 0x8, 0x1, 0xA, FLAG_F_FIELD, 0x1, 0xA}, .name = "C=R2" },
	{  .sl = 6, .v = { 0x8, 0x1, 0xA, FLAG_F_FIELD, 0x1, 0xB}, .name = "C=R3" },
	{  .sl = 6, .v = { 0x8, 0x1, 0xA, FLAG_F_FIELD, 0x1, 0xC}, .name = "C=R4" },
	{  .sl = 6, .v = { 0x8, 0x1, 0xA, FLAG_F_FIELD, 0x2, 0x0}, .name = "AR0EX" },
	{  .sl = 6, .v = { 0x8, 0x1, 0xA, FLAG_F_FIELD, 0x2, 0x1}, .name = "AR1EX" },
	{  .sl = 6, .v = { 0x8, 0x1, 0xA, FLAG_F_FIELD, 0x2, 0x2}, .name = "AR2EX" },
	{  .sl = 6, .v = { 0x8, 0x1, 0xA, FLAG_F_FIELD, 0x2, 0x3}, .name = "AR3EX" },
	{  .sl = 6, .v = { 0x8, 0x1, 0xA, FLAG_F_FIELD, 0x2, 0x4}, .name = "AR4EX" },
	{  .sl = 6, .v = { 0x8, 0x1, 0xA, FLAG_F_FIELD, 0x2, 0x8}, .name = "CR0EX" },
	{  .sl = 6, .v = { 0x8, 0x1, 0xA, FLAG_F_FIELD, 0x2, 0x9}, .name = "CR1EX" },
	{  .sl = 6, .v = { 0x8, 0x1, 0xA, FLAG_F_FIELD, 0x2, 0xA}, .name = "CR2EX" },
	{  .sl = 6, .v = { 0x8, 0x1, 0xA, FLAG_F_FIELD, 0x2, 0xB}, .name = "CR3EX" },
	{  .sl = 6, .v = { 0x8, 0x1, 0xA, FLAG_F_FIELD, 0x2, 0xC}, .name = "CR4EX" },
	{  .sl = 4, .v = { 0x8, 0x1, 0xB, 0x2}, .name = "PC=A" },
	{  .sl = 4, .v = { 0x8, 0x1, 0xB, 0x3}, .name = "PC=C" },
	{  .sl = 4, .v = { 0x8, 0x1, 0xB, 0x4}, .name = "A=PC" },
	{  .sl = 4, .v = { 0x8, 0x1, 0xB, 0x5}, .name = "C=PC" },
	{  .sl = 4, .v = { 0x8, 0x1, 0xB, 0x6}, .name = "APCEX" },
	{  .sl = 4, .v = { 0x8, 0x1, 0xB, 0x7}, .name = "CPCEX" },
	{  .sl = 3, .v = { 0x8, 0x1, 0xC}, .name = "ASRB" },
	{  .sl = 3, .v = { 0x8, 0x1, 0xD}, .name = "BSRB" },
	{  .sl = 3, .v = { 0x8, 0x1, 0xE}, .name = "CSRB" },
	{  .sl = 3, .v = { 0x8, 0x1, 0xF}, .name = "DSRB" },
	{  .sl = 3, .v = { 0x8, 0x2, 0x1}, .name = "XM=0" },
	{  .sl = 3, .v = { 0x8, 0x2, 0x2}, .name = "SB=0" },
	{  .sl = 3, .v = { 0x8, 0x2, 0x4}, .name = "SR=0" },
	{  .sl = 3, .v = { 0x8, 0x2, 0x8}, .name = "MP=0" },
	{  .sl = 3, .v = { 0x8, 0x2, 0xF}, .name = "CLRHT" },
	{  .sl = 4, .v = { 0x8, 0x3, 0x1, FLAG_ADDR2}, .name = "?XM=0" },
	{  .sl = 4, .v = { 0x8, 0x3, 0x2, FLAG_ADDR2}, .name = "?SB=0" },
	{  .sl = 4, .v = { 0x8, 0x3, 0x4, FLAG_ADDR2}, .name = "?SR=0" },
	{  .sl = 4, .v = { 0x8, 0x3, 0x8, FLAG_ADDR2}, .name = "?MP=0" },
	{  .sl = 3, .v = { 0x8, 0x4, FLAG_BIT_INDEX}, .name = "ST=0" },
	{  .sl = 3, .v = { 0x8, 0x5, FLAG_BIT_INDEX}, .name = "ST=1" },
	{  .sl = 4, .v = { 0x8, 0x6, FLAG_BIT_INDEX, FLAG_ADDR2}, .name = "?ST=0" },
	{  .sl = 4, .v = { 0x8, 0x7, FLAG_BIT_INDEX, FLAG_ADDR2}, .name = "?ST=1" },
	{  .sl = 4, .v = { 0x8, 0x8, FLAG_BIT_INDEX, FLAG_ADDR2}, .name = "?P#" },
	{  .sl = 4, .v = { 0x8, 0x9, FLAG_BIT_INDEX, FLAG_ADDR2}, .name = "?P=" },

	{  .sl = 4, .v = { 0x8, 0xA, 0x0, FLAG_ADDR2}, .name = "?B=A A" },
	{  .sl = 4, .v = { 0x8, 0xA, 0x0, FLAG_ADDR2}, .name = "?A=B A" },
	{  .sl = 4, .v = { 0x8, 0xA, 0x1, FLAG_ADDR2}, .name = "?C=B A" },
	{  .sl = 4, .v = { 0x8, 0xA, 0x1, FLAG_ADDR2}, .name = "?B=C A" },
	{  .sl = 4, .v = { 0x8, 0xA, 0x2, FLAG_ADDR2}, .name = "?A=C A" },
	{  .sl = 4, .v = { 0x8, 0xA, 0x2, FLAG_ADDR2}, .name = "?C=A A" },
	{  .sl = 4, .v = { 0x8, 0xA, 0x3, FLAG_ADDR2}, .name = "?C=D A" },
	{  .sl = 4, .v = { 0x8, 0xA, 0x3, FLAG_ADDR2}, .name = "?D=C A" },
	{  .sl = 4, .v = { 0x8, 0xA, 0x4, FLAG_ADDR2}, .name = "?B#A A" },
	{  .sl = 4, .v = { 0x8, 0xA, 0x4, FLAG_ADDR2}, .name = "?A#B A" },
	{  .sl = 4, .v = { 0x8, 0xA, 0x5, FLAG_ADDR2}, .name = "?C#B A" },
	{  .sl = 4, .v = { 0x8, 0xA, 0x5, FLAG_ADDR2}, .name = "?B#C A" },
	{  .sl = 4, .v = { 0x8, 0xA, 0x6, FLAG_ADDR2}, .name = "?A#C A" },
	{  .sl = 4, .v = { 0x8, 0xA, 0x6, FLAG_ADDR2}, .name = "?C#A A" },
	{  .sl = 4, .v = { 0x8, 0xA, 0x7, FLAG_ADDR2}, .name = "?D#C A" },
	{  .sl = 4, .v = { 0x8, 0xA, 0x7, FLAG_ADDR2}, .name = "?C#S A" },
	{  .sl = 4, .v = { 0x8, 0xA, 0x8, FLAG_ADDR2}, .name = "?A=0 A" },
	{  .sl = 4, .v = { 0x8, 0xA, 0x9, FLAG_ADDR2}, .name = "?B=0 A" },
	{  .sl = 4, .v = { 0x8, 0xA, 0xA, FLAG_ADDR2}, .name = "?C=0 A" },
	{  .sl = 4, .v = { 0x8, 0xA, 0xB, FLAG_ADDR2}, .name = "?D=0 A" },
	{  .sl = 4, .v = { 0x8, 0xA, 0xC, FLAG_ADDR2}, .name = "?A#0 A" },
	{  .sl = 4, .v = { 0x8, 0xA, 0xD, FLAG_ADDR2}, .name = "?B#0 A" },
	{  .sl = 4, .v = { 0x8, 0xA, 0xE, FLAG_ADDR2}, .name = "?C#0 A" },
	{  .sl = 4, .v = { 0x8, 0xA, 0xF, FLAG_ADDR2}, .name = "?D#0 A" },
	{  .sl = 4, .v = { 0x8, 0xB, 0x1, FLAG_ADDR2}, .name = "?B>C A" },
	{  .sl = 4, .v = { 0x8, 0xB, 0x1, FLAG_ADDR2}, .name = "?C<B A" },
	{  .sl = 4, .v = { 0x8, 0xB, 0x2, FLAG_ADDR2}, .name = "?C>A A" },
	{  .sl = 4, .v = { 0x8, 0xB, 0x2, FLAG_ADDR2}, .name = "?A<C A" },
	{  .sl = 4, .v = { 0x8, 0xB, 0x3, FLAG_ADDR2}, .name = "?D>C A" },
	{  .sl = 4, .v = { 0x8, 0xB, 0x3, FLAG_ADDR2}, .name = "?C<D A" },
	{  .sl = 4, .v = { 0x8, 0xB, 0x4, FLAG_ADDR2}, .name = "?A<B A" },
	{  .sl = 4, .v = { 0x8, 0xB, 0x4, FLAG_ADDR2}, .name = "?B>A A" },
	{  .sl = 4, .v = { 0x8, 0xB, 0x5, FLAG_ADDR2}, .name = "?B<C A" },
	{  .sl = 4, .v = { 0x8, 0xB, 0x5, FLAG_ADDR2}, .name = "?C>B A" },
	{  .sl = 4, .v = { 0x8, 0xB, 0x6, FLAG_ADDR2}, .name = "?C<A A" },
	{  .sl = 4, .v = { 0x8, 0xB, 0x6, FLAG_ADDR2}, .name = "?A>C A" },
	{  .sl = 4, .v = { 0x8, 0xB, 0x7, FLAG_ADDR2}, .name = "?D<C A" },
	{  .sl = 4, .v = { 0x8, 0xB, 0x7, FLAG_ADDR2}, .name = "?C>D A" },
	{  .sl = 4, .v = { 0x8, 0xB, 0x8, FLAG_ADDR2}, .name = "?A>=B A" },
	{  .sl = 4, .v = { 0x8, 0xB, 0x8, FLAG_ADDR2}, .name = "?B<=A A" },
	{  .sl = 4, .v = { 0x8, 0xB, 0x9, FLAG_ADDR2}, .name = "?B>=C A" },
	{  .sl = 4, .v = { 0x8, 0xB, 0x9, FLAG_ADDR2}, .name = "?C<=B A" },
	{  .sl = 4, .v = { 0x8, 0xB, 0xA, FLAG_ADDR2}, .name = "?C>=A A" },
	{  .sl = 4, .v = { 0x8, 0xB, 0xA, FLAG_ADDR2}, .name = "?A<=C A" },
	{  .sl = 4, .v = { 0x8, 0xB, 0xB, FLAG_ADDR2}, .name = "?D>=C A" },
	{  .sl = 4, .v = { 0x8, 0xB, 0xB, FLAG_ADDR2}, .name = "?C<=D A" },
	{  .sl = 4, .v = { 0x8, 0xB, 0xC, FLAG_ADDR2}, .name = "?A<=B A" },
	{  .sl = 4, .v = { 0x8, 0xB, 0xC, FLAG_ADDR2}, .name = "?B>=A A" },
	{  .sl = 4, .v = { 0x8, 0xB, 0xD, FLAG_ADDR2}, .name = "?B<=C A" },
	{  .sl = 4, .v = { 0x8, 0xB, 0xD, FLAG_ADDR2}, .name = "?C>=B A" },
	{  .sl = 4, .v = { 0x8, 0xB, 0xE, FLAG_ADDR2}, .name = "?C<=A A" },
	{  .sl = 4, .v = { 0x8, 0xB, 0xE, FLAG_ADDR2}, .name = "?A>=C A" },
	{  .sl = 4, .v = { 0x8, 0xB, 0xF, FLAG_ADDR2}, .name = "?D<=C A" },
	{  .sl = 4, .v = { 0x8, 0xB, 0xF, FLAG_ADDR2}, .name = "?C>=D A" },

	{  .sl = 3, .v = { 0x8, 0xC, FLAG_ADDR4}, .name = "GOLONG" },
	{  .sl = 3, .v = { 0x8, 0xD, FLAG_ADDR5}, .name = "GOVLNG" },
	{  .sl = 3, .v = { 0x8, 0xE, FLAG_ADDR4}, .name = "GOSUBL" },
	{  .sl = 3, .v = { 0x8, 0xF, FLAG_ADDR5}, .name = "GOSBVL" },

	{  .sl = 4, .v = { 0x9, FLAG_A_FIELD, 0x0, FLAG_ADDR2}, .name = "?B=A" },
	{  .sl = 4, .v = { 0x9, FLAG_A_FIELD, 0x0, FLAG_ADDR2}, .name = "?A=B" },
	{  .sl = 4, .v = { 0x9, FLAG_A_FIELD, 0x1, FLAG_ADDR2}, .name = "?C=B" },
	{  .sl = 4, .v = { 0x9, FLAG_A_FIELD, 0x1, FLAG_ADDR2}, .name = "?B=C" },
	{  .sl = 4, .v = { 0x9, FLAG_A_FIELD, 0x2, FLAG_ADDR2}, .name = "?A=C" },
	{  .sl = 4, .v = { 0x9, FLAG_A_FIELD, 0x2, FLAG_ADDR2}, .name = "?C=A" },
	{  .sl = 4, .v = { 0x9, FLAG_A_FIELD, 0x3, FLAG_ADDR2}, .name = "?C=D" },
	{  .sl = 4, .v = { 0x9, FLAG_A_FIELD, 0x3, FLAG_ADDR2}, .name = "?D=C" },
	{  .sl = 4, .v = { 0x9, FLAG_A_FIELD, 0x4, FLAG_ADDR2}, .name = "?B#A" },
	{  .sl = 4, .v = { 0x9, FLAG_A_FIELD, 0x4, FLAG_ADDR2}, .name = "?A#B" },
	{  .sl = 4, .v = { 0x9, FLAG_A_FIELD, 0x5, FLAG_ADDR2}, .name = "?C#B" },
	{  .sl = 4, .v = { 0x9, FLAG_A_FIELD, 0x5, FLAG_ADDR2}, .name = "?B#C" },
	{  .sl = 4, .v = { 0x9, FLAG_A_FIELD, 0x6, FLAG_ADDR2}, .name = "?A#C" },
	{  .sl = 4, .v = { 0x9, FLAG_A_FIELD, 0x6, FLAG_ADDR2}, .name = "?C#A" },
	{  .sl = 4, .v = { 0x9, FLAG_A_FIELD, 0x7, FLAG_ADDR2}, .name = "?D#C" },
	{  .sl = 4, .v = { 0x9, FLAG_A_FIELD, 0x7, FLAG_ADDR2}, .name = "?C#D" },
	{  .sl = 4, .v = { 0x9, FLAG_A_FIELD, 0x8, FLAG_ADDR2}, .name = "?A=0" },
	{  .sl = 4, .v = { 0x9, FLAG_A_FIELD, 0x9, FLAG_ADDR2}, .name = "?B=0" },
	{  .sl = 4, .v = { 0x9, FLAG_A_FIELD, 0xA, FLAG_ADDR2}, .name = "?C=0" },
	{  .sl = 4, .v = { 0x9, FLAG_A_FIELD, 0xB, FLAG_ADDR2}, .name = "?D=0" },
	{  .sl = 4, .v = { 0x9, FLAG_A_FIELD, 0xC, FLAG_ADDR2}, .name = "?A#0" },
	{  .sl = 4, .v = { 0x9, FLAG_A_FIELD, 0xD, FLAG_ADDR2}, .name = "?B#0" },
	{  .sl = 4, .v = { 0x9, FLAG_A_FIELD, 0xE, FLAG_ADDR2}, .name = "?C#0" },
	{  .sl = 4, .v = { 0x9, FLAG_A_FIELD, 0xF, FLAG_ADDR2}, .name = "?D#0" },
	{  .sl = 4, .v = { 0x9, FLAG_B_FIELD, 0x1, FLAG_ADDR2}, .name = "?B>C" },
	{  .sl = 4, .v = { 0x9, FLAG_B_FIELD, 0x1, FLAG_ADDR2}, .name = "?C<B" },
	{  .sl = 4, .v = { 0x9, FLAG_B_FIELD, 0x2, FLAG_ADDR2}, .name = "?C>A" },
	{  .sl = 4, .v = { 0x9, FLAG_B_FIELD, 0x2, FLAG_ADDR2}, .name = "?A<C" },
	{  .sl = 4, .v = { 0x9, FLAG_B_FIELD, 0x3, FLAG_ADDR2}, .name = "?D>C" },
	{  .sl = 4, .v = { 0x9, FLAG_B_FIELD, 0x3, FLAG_ADDR2}, .name = "?C<D" },
	{  .sl = 4, .v = { 0x9, FLAG_B_FIELD, 0x4, FLAG_ADDR2}, .name = "?A<B" },
	{  .sl = 4, .v = { 0x9, FLAG_B_FIELD, 0x4, FLAG_ADDR2}, .name = "?B>A" },
	{  .sl = 4, .v = { 0x9, FLAG_B_FIELD, 0x5, FLAG_ADDR2}, .name = "?B<C" },
	{  .sl = 4, .v = { 0x9, FLAG_B_FIELD, 0x5, FLAG_ADDR2}, .name = "?C>B" },
	{  .sl = 4, .v = { 0x9, FLAG_B_FIELD, 0x6, FLAG_ADDR2}, .name = "?C<A" },
	{  .sl = 4, .v = { 0x9, FLAG_B_FIELD, 0x6, FLAG_ADDR2}, .name = "?A>C" },
	{  .sl = 4, .v = { 0x9, FLAG_B_FIELD, 0x7, FLAG_ADDR2}, .name = "?D<C" },
	{  .sl = 4, .v = { 0x9, FLAG_B_FIELD, 0x7, FLAG_ADDR2}, .name = "?C>D" },
	{  .sl = 4, .v = { 0x9, FLAG_B_FIELD, 0x8, FLAG_ADDR2}, .name = "?A>=B" },
	{  .sl = 4, .v = { 0x9, FLAG_B_FIELD, 0x8, FLAG_ADDR2}, .name = "?B<=A" },
	{  .sl = 4, .v = { 0x9, FLAG_B_FIELD, 0x9, FLAG_ADDR2}, .name = "?B>=C" },
	{  .sl = 4, .v = { 0x9, FLAG_B_FIELD, 0x9, FLAG_ADDR2}, .name = "?C<=B" },
	{  .sl = 4, .v = { 0x9, FLAG_B_FIELD, 0xA, FLAG_ADDR2}, .name = "?C>=A" },
	{  .sl = 4, .v = { 0x9, FLAG_B_FIELD, 0xA, FLAG_ADDR2}, .name = "?A<=C" },
	{  .sl = 4, .v = { 0x9, FLAG_B_FIELD, 0xB, FLAG_ADDR2}, .name = "?D>=C" },
	{  .sl = 4, .v = { 0x9, FLAG_B_FIELD, 0xB, FLAG_ADDR2}, .name = "?C<=D" },
	{  .sl = 4, .v = { 0x9, FLAG_B_FIELD, 0xC, FLAG_ADDR2}, .name = "?A<=B" },
	{  .sl = 4, .v = { 0x9, FLAG_B_FIELD, 0xC, FLAG_ADDR2}, .name = "?B>=A" },
	{  .sl = 4, .v = { 0x9, FLAG_B_FIELD, 0xD, FLAG_ADDR2}, .name = "?B<=C" },
	{  .sl = 4, .v = { 0x9, FLAG_B_FIELD, 0xD, FLAG_ADDR2}, .name = "?C>=B" },
	{  .sl = 4, .v = { 0x9, FLAG_B_FIELD, 0xE, FLAG_ADDR2}, .name = "?C<=A" },
	{  .sl = 4, .v = { 0x9, FLAG_B_FIELD, 0xE, FLAG_ADDR2}, .name = "?A>=C" },
	{  .sl = 4, .v = { 0x9, FLAG_B_FIELD, 0xF, FLAG_ADDR2}, .name = "?D<=C" },
	{  .sl = 4, .v = { 0x9, FLAG_B_FIELD, 0xF, FLAG_ADDR2}, .name = "?C>=D" },

	{  .sl = 3, .v = { 0xA, FLAG_A_FIELD, 0x0 }, .name = "A=A+B" },
	{  .sl = 3, .v = { 0xA, FLAG_A_FIELD, 0x1 }, .name = "B=B+C" },
	{  .sl = 3, .v = { 0xA, FLAG_A_FIELD, 0x2 }, .name = "C=C+A" },
	{  .sl = 3, .v = { 0xA, FLAG_A_FIELD, 0x3 }, .name = "D=D+C" },
	{  .sl = 3, .v = { 0xA, FLAG_A_FIELD, 0x4 }, .name = "A=A+A" },
	{  .sl = 3, .v = { 0xA, FLAG_A_FIELD, 0x5 }, .name = "B=B+B" },
	{  .sl = 3, .v = { 0xA, FLAG_A_FIELD, 0x6 }, .name = "C=C+C" },
	{  .sl = 3, .v = { 0xA, FLAG_A_FIELD, 0x7 }, .name = "D=D+D" },
	{  .sl = 3, .v = { 0xA, FLAG_A_FIELD, 0x8 }, .name = "B=B+A" },
	{  .sl = 3, .v = { 0xA, FLAG_A_FIELD, 0x9 }, .name = "C=C+B" },
	{  .sl = 3, .v = { 0xA, FLAG_A_FIELD, 0xA }, .name = "A=A+C" },
	{  .sl = 3, .v = { 0xA, FLAG_A_FIELD, 0xB }, .name = "C=C+D" },
	{  .sl = 3, .v = { 0xA, FLAG_A_FIELD, 0xC }, .name = "A=A-1" },
	{  .sl = 3, .v = { 0xA, FLAG_A_FIELD, 0xD }, .name = "B=B-1" },
	{  .sl = 3, .v = { 0xA, FLAG_A_FIELD, 0xE }, .name = "C=C-1" },
	{  .sl = 3, .v = { 0xA, FLAG_A_FIELD, 0xF }, .name = "D=D-1" },

	{  .sl = 3, .v = { 0xA, FLAG_B_FIELD, 0x0 }, .name = "A=0" },
	{  .sl = 3, .v = { 0xA, FLAG_B_FIELD, 0x1 }, .name = "B=0" },
	{  .sl = 3, .v = { 0xA, FLAG_B_FIELD, 0x2 }, .name = "C=0" },
	{  .sl = 3, .v = { 0xA, FLAG_B_FIELD, 0x3 }, .name = "D=0" },
	{  .sl = 3, .v = { 0xA, FLAG_B_FIELD, 0x4 }, .name = "A=B" },
	{  .sl = 3, .v = { 0xA, FLAG_B_FIELD, 0x5 }, .name = "B=C" },
	{  .sl = 3, .v = { 0xA, FLAG_B_FIELD, 0x6 }, .name = "C=A" },
	{  .sl = 3, .v = { 0xA, FLAG_B_FIELD, 0x7 }, .name = "D=C" },
	{  .sl = 3, .v = { 0xA, FLAG_B_FIELD, 0x8 }, .name = "B=A" },
	{  .sl = 3, .v = { 0xA, FLAG_B_FIELD, 0x9 }, .name = "C=B" },
	{  .sl = 3, .v = { 0xA, FLAG_B_FIELD, 0xA }, .name = "A=C" },
	{  .sl = 3, .v = { 0xA, FLAG_B_FIELD, 0xB }, .name = "C=D" },
	{  .sl = 3, .v = { 0xA, FLAG_B_FIELD, 0xC }, .name = "ABEX" },
	{  .sl = 3, .v = { 0xA, FLAG_B_FIELD, 0xC }, .name = "BAEX" },
	{  .sl = 3, .v = { 0xA, FLAG_B_FIELD, 0xD }, .name = "BCEX" },
	{  .sl = 3, .v = { 0xA, FLAG_B_FIELD, 0xD }, .name = "CBEX" },
	{  .sl = 3, .v = { 0xA, FLAG_B_FIELD, 0xE }, .name = "ACEX" },
	{  .sl = 3, .v = { 0xA, FLAG_B_FIELD, 0xE }, .name = "CAEX" },
	{  .sl = 3, .v = { 0xA, FLAG_B_FIELD, 0xF }, .name = "CDEX" },
	{  .sl = 3, .v = { 0xA, FLAG_B_FIELD, 0xF }, .name = "DCEX" },

	{  .sl = 3, .v = { 0xB, FLAG_A_FIELD, 0x0 }, .name = "A=A-B" },
	{  .sl = 3, .v = { 0xB, FLAG_A_FIELD, 0x1 }, .name = "B=B-C" },
	{  .sl = 3, .v = { 0xB, FLAG_A_FIELD, 0x2 }, .name = "C=C-A" },
	{  .sl = 3, .v = { 0xB, FLAG_A_FIELD, 0x3 }, .name = "D=D-C" },
	{  .sl = 3, .v = { 0xB, FLAG_A_FIELD, 0x4 }, .name = "A=A+1" },
	{  .sl = 3, .v = { 0xB, FLAG_A_FIELD, 0x5 }, .name = "B=B+1" },
	{  .sl = 3, .v = { 0xB, FLAG_A_FIELD, 0x6 }, .name = "C=C+1" },
	{  .sl = 3, .v = { 0xB, FLAG_A_FIELD, 0x7 }, .name = "D=D+1" },
	{  .sl = 3, .v = { 0xB, FLAG_A_FIELD, 0x8 }, .name = "B=B-A" },
	{  .sl = 3, .v = { 0xB, FLAG_A_FIELD, 0x9 }, .name = "C=C-B" },
	{  .sl = 3, .v = { 0xB, FLAG_A_FIELD, 0xA }, .name = "A=A-C" },
	{  .sl = 3, .v = { 0xB, FLAG_A_FIELD, 0xB }, .name = "C=C-D" },
	{  .sl = 3, .v = { 0xB, FLAG_A_FIELD, 0xC }, .name = "A=B-A" },
	{  .sl = 3, .v = { 0xB, FLAG_A_FIELD, 0xD }, .name = "B=C-B" },
	{  .sl = 3, .v = { 0xB, FLAG_A_FIELD, 0xE }, .name = "C=A-C" },
	{  .sl = 3, .v = { 0xB, FLAG_A_FIELD, 0xF }, .name = "D=C-D" },

	{  .sl = 3, .v = { 0xB, FLAG_B_FIELD, 0x0 }, .name = "ASL" },
	{  .sl = 3, .v = { 0xB, FLAG_B_FIELD, 0x1 }, .name = "BSL" },
	{  .sl = 3, .v = { 0xB, FLAG_B_FIELD, 0x2 }, .name = "CSL" },
	{  .sl = 3, .v = { 0xB, FLAG_B_FIELD, 0x3 }, .name = "DSL" },
	{  .sl = 3, .v = { 0xB, FLAG_B_FIELD, 0x4 }, .name = "ASR" },
	{  .sl = 3, .v = { 0xB, FLAG_B_FIELD, 0x5 }, .name = "BSR" },
	{  .sl = 3, .v = { 0xB, FLAG_B_FIELD, 0x6 }, .name = "CSR" },
	{  .sl = 3, .v = { 0xB, FLAG_B_FIELD, 0x7 }, .name = "DSR" },
	{  .sl = 3, .v = { 0xB, FLAG_B_FIELD, 0x8 }, .name = "A=-A" },
	{  .sl = 3, .v = { 0xB, FLAG_B_FIELD, 0x9 }, .name = "B=-B" },
	{  .sl = 3, .v = { 0xB, FLAG_B_FIELD, 0xA }, .name = "C=-C" },
	{  .sl = 3, .v = { 0xB, FLAG_B_FIELD, 0xB }, .name = "D=-D" },
	{  .sl = 3, .v = { 0xB, FLAG_B_FIELD, 0xC }, .name = "A=-A-1" },
	{  .sl = 3, .v = { 0xB, FLAG_B_FIELD, 0xD }, .name = "B=-B-1" },
	{  .sl = 3, .v = { 0xB, FLAG_B_FIELD, 0xE }, .name = "C=-C-1" },
	{  .sl = 3, .v = { 0xB, FLAG_B_FIELD, 0xF }, .name = "D=-D-1" },

	{  .sl = 2, .v = { 0xC, 0x0 }, .name = "A=A+B A" },
	{  .sl = 2, .v = { 0xC, 0x1 }, .name = "B=B+C A" },
	{  .sl = 2, .v = { 0xC, 0x2 }, .name = "C=C+A A" },
	{  .sl = 2, .v = { 0xC, 0x3 }, .name = "D=D+C A" },
	{  .sl = 2, .v = { 0xC, 0x4 }, .name = "A=A+A A" },
	{  .sl = 2, .v = { 0xC, 0x5 }, .name = "B=B+B A" },
	{  .sl = 2, .v = { 0xC, 0x6 }, .name = "C=C+C A" },
	{  .sl = 2, .v = { 0xC, 0x7 }, .name = "D=D+D A" },
	{  .sl = 2, .v = { 0xC, 0x8 }, .name = "B=B+A A" },
	{  .sl = 2, .v = { 0xC, 0x9 }, .name = "C=C+B A" },
	{  .sl = 2, .v = { 0xC, 0xA }, .name = "A=A+C A" },
	{  .sl = 2, .v = { 0xC, 0xB }, .name = "C=C+D A" },
	{  .sl = 2, .v = { 0xC, 0xC }, .name = "A=A-1 A" },
	{  .sl = 2, .v = { 0xC, 0xD }, .name = "B=B-1 A" },
	{  .sl = 2, .v = { 0xC, 0xE }, .name = "C=C-1 A" },
	{  .sl = 2, .v = { 0xC, 0xF }, .name = "D=D-1 A" },

	{  .sl = 2, .v = { 0xD, 0x0 }, .name = "A=0 A" },
	{  .sl = 2, .v = { 0xD, 0x1 }, .name = "B=0 A" },
	{  .sl = 2, .v = { 0xD, 0x2 }, .name = "C=0 A" },
	{  .sl = 2, .v = { 0xD, 0x3 }, .name = "D=0 A" },
	{  .sl = 2, .v = { 0xD, 0x4 }, .name = "A=B A" },
	{  .sl = 2, .v = { 0xD, 0x5 }, .name = "B=C A" },
	{  .sl = 2, .v = { 0xD, 0x6 }, .name = "C=A A" },
	{  .sl = 2, .v = { 0xD, 0x7 }, .name = "D=C A" },
	{  .sl = 2, .v = { 0xD, 0x8 }, .name = "B=A A" },
	{  .sl = 2, .v = { 0xD, 0x9 }, .name = "C=B A" },
	{  .sl = 2, .v = { 0xD, 0xA }, .name = "A=C A" },
	{  .sl = 2, .v = { 0xD, 0xB }, .name = "C=D A" },

	{  .sl = 2, .v = { 0xE, 0x0 }, .name = "A=A-B A" },
	{  .sl = 2, .v = { 0xE, 0x1 }, .name = "B=B-C A" },
	{  .sl = 2, .v = { 0xE, 0x2 }, .name = "C=C-A A" },
	{  .sl = 2, .v = { 0xE, 0x3 }, .name = "D=D-C A" },
	{  .sl = 2, .v = { 0xE, 0x4 }, .name = "A=A+1 A" },
	{  .sl = 2, .v = { 0xE, 0x5 }, .name = "B=B+1 A" },
	{  .sl = 2, .v = { 0xE, 0x6 }, .name = "C=C+1 A" },
	{  .sl = 2, .v = { 0xE, 0x7 }, .name = "D=D+1 A" },
	{  .sl = 2, .v = { 0xE, 0x8 }, .name = "B=B-A A" },
	{  .sl = 2, .v = { 0xE, 0x9 }, .name = "C=C-B A" },
	{  .sl = 2, .v = { 0xE, 0xA }, .name = "A=A-C A" },
	{  .sl = 2, .v = { 0xE, 0xB }, .name = "C=C-D A" },
	{  .sl = 2, .v = { 0xE, 0xC }, .name = "A=B-A A" },
	{  .sl = 2, .v = { 0xE, 0xD }, .name = "B=C-B A" },
	{  .sl = 2, .v = { 0xE, 0xE }, .name = "C=A-C A" },
	{  .sl = 2, .v = { 0xE, 0xF }, .name = "D=C-D A" },

	{  .sl = 2, .v = { 0xF, 0x0 }, .name = "ASL A" },
	{  .sl = 2, .v = { 0xF, 0x1 }, .name = "BSL A" },
	{  .sl = 2, .v = { 0xF, 0x2 }, .name = "CSL A" },
	{  .sl = 2, .v = { 0xF, 0x3 }, .name = "DSL A" },
	{  .sl = 2, .v = { 0xF, 0x4 }, .name = "ASR A" },
	{  .sl = 2, .v = { 0xF, 0x5 }, .name = "BSR A" },
	{  .sl = 2, .v = { 0xF, 0x6 }, .name = "CSR A" },
	{  .sl = 2, .v = { 0xF, 0x7 }, .name = "DSR A" },
	{  .sl = 2, .v = { 0xF, 0x8 }, .name = "A=-A A" },
	{  .sl = 2, .v = { 0xF, 0x9 }, .name = "B=-B A" },
	{  .sl = 2, .v = { 0xF, 0xA }, .name = "C=-C A" },
	{  .sl = 2, .v = { 0xF, 0xB }, .name = "D=-D A" },
	{  .sl = 2, .v = { 0xF, 0xC }, .name = "A=-A-1 A" },
	{  .sl = 2, .v = { 0xF, 0xD }, .name = "B=-B-1 A" },
	{  .sl = 2, .v = { 0xF, 0xE }, .name = "C=-C-1 A" },
	{  .sl = 2, .v = { 0xF, 0xF }, .name = "D=-D-1 A" },

	/* later to prevent mistakes with any comment */
	{  .sl = 6, .v = { 0x8, 0x1, 0x8, FLAG_F_FIELD, 0x0, FLAG_DEC }, .name = "A=A+$" },
	{  .sl = 6, .v = { 0x8, 0x1, 0x8, FLAG_F_FIELD, 0x1, FLAG_DEC }, .name = "B=B+$" },
	{  .sl = 6, .v = { 0x8, 0x1, 0x8, FLAG_F_FIELD, 0x2, FLAG_DEC }, .name = "C=C+$" },
	{  .sl = 6, .v = { 0x8, 0x1, 0x8, FLAG_F_FIELD, 0x3, FLAG_DEC }, .name = "D=D+$" },
	{  .sl = 6, .v = { 0x8, 0x1, 0x8, FLAG_F_FIELD, 0x8, FLAG_DEC }, .name = "A=A-$" },
	{  .sl = 6, .v = { 0x8, 0x1, 0x8, FLAG_F_FIELD, 0x9, FLAG_DEC }, .name = "B=B-$" },
	{  .sl = 6, .v = { 0x8, 0x1, 0x8, FLAG_F_FIELD, 0xA, FLAG_DEC }, .name = "C=C-$" },
	{  .sl = 6, .v = { 0x8, 0x1, 0x8, FLAG_F_FIELD, 0xB, FLAG_DEC }, .name = "D=D-$" },


	{  .sl = 2, .v = { 0xF, 0x0 }, .name = "ASL" },
	{  .sl = 2, .v = { 0xF, 0x1 }, .name = "BSL" },
	{  .sl = 2, .v = { 0xF, 0x2 }, .name = "CSL" },
	{  .sl = 2, .v = { 0xF, 0x3 }, .name = "DSL" },
	{  .sl = 2, .v = { 0xF, 0x4 }, .name = "ASR" },
	{  .sl = 2, .v = { 0xF, 0x5 }, .name = "BSR" },
	{  .sl = 2, .v = { 0xF, 0x6 }, .name = "CSR" },
	{  .sl = 2, .v = { 0xF, 0x7 }, .name = "DSR" },
	{  .sl = 2, .v = { 0xF, 0x8 }, .name = "A=-A A" },
	{  .sl = 2, .v = { 0xF, 0x9 }, .name = "B=-B A" },
	{  .sl = 2, .v = { 0xF, 0xA }, .name = "C=-C A" },
	{  .sl = 2, .v = { 0xF, 0xB }, .name = "D=-D A" },
	{  .sl = 2, .v = { 0xF, 0xC }, .name = "A=-A-1 A" },
	{  .sl = 2, .v = { 0xF, 0xD }, .name = "B=-B-1 A" },
	{  .sl = 2, .v = { 0xF, 0xE }, .name = "C=-C-1 A" },
	{  .sl = 2, .v = { 0xF, 0xF }, .name = "D=-D-1 A" },

	/* il field is specified, related defines are earlier */
	{  .sl = 3, .v = { 0x1, 0x0, 0x0 }, .name = "R0=A" },
	{  .sl = 3, .v = { 0x1, 0x0, 0x1 }, .name = "R1=A" },
	{  .sl = 3, .v = { 0x1, 0x0, 0x2 }, .name = "R2=A" },
	{  .sl = 3, .v = { 0x1, 0x0, 0x3 }, .name = "R3=A" },
	{  .sl = 3, .v = { 0x1, 0x0, 0x4 }, .name = "R4=A" },
	{  .sl = 3, .v = { 0x1, 0x0, 0x8 }, .name = "R0=C" },
	{  .sl = 3, .v = { 0x1, 0x0, 0x9 }, .name = "R1=C" },
	{  .sl = 3, .v = { 0x1, 0x0, 0xA }, .name = "R2=C" },
	{  .sl = 3, .v = { 0x1, 0x0, 0xB }, .name = "R3=C" },
	{  .sl = 3, .v = { 0x1, 0x0, 0xC }, .name = "R4=C" },
	{  .sl = 3, .v = { 0x1, 0x1, 0x0 }, .name = "A=R0" },
	{  .sl = 3, .v = { 0x1, 0x1, 0x1 }, .name = "A=R1" },
	{  .sl = 3, .v = { 0x1, 0x1, 0x2 }, .name = "A=R2" },
	{  .sl = 3, .v = { 0x1, 0x1, 0x3 }, .name = "A=R3" },
	{  .sl = 3, .v = { 0x1, 0x1, 0x4 }, .name = "A=R4" },
	{  .sl = 3, .v = { 0x1, 0x1, 0x8 }, .name = "C=R0" },
	{  .sl = 3, .v = { 0x1, 0x1, 0x9 }, .name = "C=R1" },
	{  .sl = 3, .v = { 0x1, 0x1, 0xA }, .name = "C=R2" },
	{  .sl = 3, .v = { 0x1, 0x1, 0xB }, .name = "C=R3" },
	{  .sl = 3, .v = { 0x1, 0x1, 0xC }, .name = "C=R4" },
}
;


#ifndef SIZEOF_ARRAY
#define SIZEOF_ARRAY(a) ((sizeof(a) / (sizeof(*(a)))))
#endif

int instructions_nb = SIZEOF_ARRAY(instructions);
